### ISSUE TITLE
NotEnoughInfo not explicitly mentioned

### ISSUE THREAD

**Issue by jacklxc** [allenai/scifact#1]
In the paper, abstracts are labeled SUPPORTS, REFUTES, NotEnoughInfo respect to claims, but there is no NotEnoughInfo label in the dataset provided. Do you assume for each claim, not explicitly labeled abstracts are all NotEnoughInfo?

**Comment by PeterL1n** [comment]
Yes. If the claim does not have any evidence, then it is NOT_ENOUGH_INFO.
