### ISSUE TITLE
experimental reports for verifying the 36 claims

### ISSUE THREAD

**Issue by jadecranberry** [allenai/scifact#20]
Hi David,
Where could I find the full reports for verifying the 36 claims? In your paper, it just showed two examples. I've run your code and just want to check if my results are correct. Thanks a lot!

**Comment by dwadden** [comment]
As far as I know, the code should give you correct results. 

That said, I did a little digging to try to find the predictions. You can download them from Google Drive by clicking [this link](https://drive.google.com/file/d/1FnIHrURvjWSQ09Lk3a_014jriu35g2gr/view?usp=sharing).

Unfortunately I can't offer "official support" for this, meaning I can't help debug of the predictions in the file don't match up with what you're getting. But hopefully it will be useful.
