### ISSUE TITLE
The covidex ai website is down

### ISSUE THREAD

**Issue by jadecranberry** [allenai/scifact#21]
Hi David,
I just found the website used to extract the abstracts was offline for a few days now and I can't run the experiments anymore. I just wonder if this would be permanently offline? Thanks.

**Comment by dwadden** [comment]
Unfortunately, I'm not part of the covidex team. I think your best bet is to contact the paper authors: https://arxiv.org/abs/2007.07846.

Lacking Covidex, your best bet would probably be to download the [cord-19 corpus](https://www.semanticscholar.org/cord19) and then implement retrieval. The same group that made Covidex is in charge of [pyserini](https://github.com/castorini/pyserini), so you might be able to work with the paper authors to get something working.

Sorry I can't help more.

**Comment by jadecranberry** [comment]
Thanks David, I contacted them and the server is now back online :)

**Comment by dwadden** [comment]
Nice!
