### ISSUE TITLE
Different results for label prediction

### ISSUE THREAD

**Issue by msadat3** [allenai/scifact#26]
Hi,

I tried to reproduce the label prediction results reported in Table 3 by using the following command:

./script/label-prediction.sh roberta_base scifact dev

I get the following output:

Accuracy           0.6168
Macro F1:          0.5478
Macro F1 w/o NEI:  0.4449

C      N      S     
F1:                [0.2703 0.7536 0.6196]
Precision:         [0.375  0.6341 0.6752]
Recall:            [0.2113 0.9286 0.5725]

Confusion Matrix:
[[ 15  24  32]
 [  2 104   6]
 [ 23  36  79]]

As we can see, the accuracy is lower than the one reported in the paper (62.9%). I am also getting a lower accuracy for roberta_large. Is this expected? Thanks in advance.

**Comment by dwadden** [comment]
Hi,

I'll try to take a look later in the week, probably Friday.

Dave

**Comment by dwadden** [comment]
Hi,

I ran the command you posted and the output I get is consistent with the results in the table. Full console output below. Maybe it's a versioning issue? Can you confirm that you've installed dependencies exactly as specified in the README? If that's not the issue, I can send you the intermediate outputs I get from `label-prediction.sh`  so that we can track down where things are different.

Dave

```
(scifact) $ ./script/label-prediction.sh roberta_base scifact dev
Running pipeline on dev set.
Data directory already exists. Skip download.
Model label_roberta_base_scifact already exists. Skip download.

Retrieving oracle abstracts.

Selecting oracle rationales.

Predicting labels.
claim_and_rationale
Using device "cuda"
100%|███████████████████████████████████████████████████████████████████████████████████████| 300/300 [00:04<00:00, 71.67it/s]

Evaluating.
Accuracy           0.6293
Macro F1:          0.5635
Macro F1 w/o NEI:  0.4498

                   [C      N      S     ]
F1:                [0.2712 0.7909 0.6284]
Precision:         [0.3404 0.6887 0.6667]
Recall:            [0.2254 0.9286 0.5942]

Confusion Matrix:
[[ 16  20  35]
 [  2 104   6]
 [ 29  27  82]]
```

**Comment by dwadden** [comment]
Ah I see, that's weird about the dependencies, I'm pretty sure I didn't have this problem when I created the repo. 
To fix it, I altered `requirements.txt` by setting `urllib3==1.25.11`. Things installed OK, and prediction worked the same as before.

Can you confirm that this works for you and I'll update the `requirements.txt` file accordingly?

**Comment by msadat3** [comment]
Thanks for looking into it.

Yes, the dependency issue gets solved but the program still gets stuck and exits with the aforementioned error.

I updated this [line](https://github.com/allenai/scifact/blob/master/verisci/inference/label_prediction/transformer.py#L29) to the following:

```
model = AutoModelForSequenceClassification.from_pretrained(args.model, config=config).eval()
print('model loaded')
model = model.to(device)
print('model moved to cuda')
```
It looks like the issue is with moving the model to cuda because it gets stuck after printing 'model loaded.' My CUDA version is 11.4. Maybe I need an older version?

**Comment by dwadden** [comment]
That might be it. The version I'm using has CUDA 11.2. Is there any way for you to check whether it works with an older version?

**Comment by msadat3** [comment]
I do not think so since mine is a shared server. Any pointers on where the new version of transformers (compatible with cuda 11.4) could be doing things differently which results in a different score?

**Comment by dwadden** [comment]
Unfortunately, I don't have any ideas other than identifying specific examples where the prediction changes and then trying to debug the forward pass of the model (i.e. look at activations at each layer). This would likely be painful. 
If you're able to localize the change to the version of `transformers` being used, you might be able to get help if you post an issue on the Huggingface website.
Other than that, I'm sorry to say that I can't really offer more help if you're using different software than I've used. I'll update the README to specify the version of CUDA that I used to get my results.
One final idea would be to try running inference on CPU and see if you can match my results that way?

**Comment by msadat3** [comment]
I completely understand. Thanks for all your help. 

Yes, I was able to reproduce your results when I ran on CPU.

**Comment by dwadden** [comment]
OK, I'm glad the CPU results work at least. Sorry we couldn't get to the bottom of it... GPU's are mysterious.

**Comment by msadat3** [comment]
No problem at all. I will let you know if I can figure out a fix. Thanks again.
