### ISSUE TITLE
Can't download the models

### ISSUE THREAD

**Issue by wjddd** [allenai/scifact#9]
Hi, I tried to download the models via this address: https://scifact.s3-us-west-2.amazonaws.com/release/latest/models/

But I got error messages as follows: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>FD5EED5C4C5847ED</RequestId>
<HostId>NktSQh7uRKZSVO08Z31RUypZEKyFwV4o/G80/YZecMZpHIuz8M7vS2SYFYWyGqyVuAUndn5h5c8=</HostId>
</Error>

How can I download the models directly from the address ?

Thank you.

**Comment by dwadden** [comment]
You can download individual models by using this script: https://github.com/allenai/scifact/blob/master/script/download-model.sh.

For instance, `bash script/download-model.sh label scibert scifact`.

I don't think there's a way to download the entire S3 bucket with a single command, but on lines 6-8 of the download script it specifies the allowed values for each argument, so you could just write a script that loops over the allowed values and downloads the models. Some combinations won't have a model available, but most will.

Let me know if this doesn't work.
